### ISSUE TITLE
Not on pypi

### ISSUE THREAD

**Issue by tensor8** [FedericoCeratto/dashing#1]
>pip2 install dashing
Collecting dashing
  Could not find a version that satisfies the requirement dashing (from versions: )
No matching distribution found for dashing

>pip3 install dashing
Collecting dashing
  Could not find a version that satisfies the requirement dashing (from versions: )
No matching distribution found for dashing

**Comment by FedericoCeratto** [comment]
Alpha version uploaded to PyPI
