### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by EbbeVang** [FedericoCeratto/dashing#11]
when I try your example i get this error:
```
ui = HSplit(
NameError: name 'HSplit' is not defined
```

I'm a bit sad because the library looks so promising :-)

**Comment by KeepSummerSaf3** [comment]
from dashing import * help?
Using pip version 0.1.0 (have not tried from source)

**Comment by neelabalan** [comment]
I am too getting this error. How to solve this?

**Comment by RPINerd** [comment]
I was getting this issue with my testing on 3.10, but my linter pointed out that * imports don't work like they used to. By manually importing the names explicity everything worked as desired i.e.:

from dashing import HSplit, VSplit, log, etc
