### ISSUE TITLE
QuickDash() is missing and can't be imported.

### ISSUE THREAD

**Issue by michaelshumshum** [FedericoCeratto/dashing#7]
i dont' want to go into normal mode cuz this dashboard isn't supposed to be the main thing. quickdash seems to be a perfect option, but it's not even in the module.

**Comment by staythecurse** [comment]
I ran into this same issue.  It looks like the code existed somewhere at some point.

To the original author @FedericoCeratto :  Can you upload the code for the QuickDash() function even if it's incomplete or commented out so that we can attempt to finish and integrate it?

**Comment by michaelshumshum** [comment]
> I ran into this same issue. It looks like the code existed somewhere at some point.
> 
> To the original author @FedericoCeratto : Can you upload the code for the QuickDash() function even if it's incomplete or commented out so that we can attempt to finish and integrate it?

**Comment by michaelshumshum** [comment]
it doesn't look like he's going to reimplement anytime soon. running the demo even shows some incomplete code, such as dysfunctional log widgets and text box. there are a lot of things this module can do that the already existing npyscreen module can d. might as well use npyscreen and curses as it has better documentation and already complete code.

**Comment by FedericoCeratto** [comment]
The demo contains working examples. QuickDash is not ready and I'm removing it from the README.
Pull requests are welcome.
